name: IllusionMina
version: 1.1
main: tigre.illusion.IllusionPlugin
api-version: '1.21'
author: MKK
description: Sistema de Mina Privada Instanciada com Packet-System.
commands:
  mina:
    description: Teleporta para a mina privada
    usage: /mina [sair|resetar]
    aliases: [mp]
permissions:
  illusion.mina.use:
    description: Permite usar a mina
    default: true